{{- if .Values.networkPolicies.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-allow-route-ingress
  labels:
{{ include "digital-marketplace.labels" . | indent 4}}
spec:
  # This policy allows any pod with a route & service combination
  # to accept traffic from the OpenShift router pods. This is
  # required for things outside of OpenShift (like the Internet)
  # to reach your pods.
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  podSelector: {}
  policyTypes:
    - Ingress
{{- end }}
